@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mrh0.createaddition.blocks.creative_energy;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;