@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mrh0.createaddition.blocks.barbed_wire;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;